services:
  # Backend API
  - type: web
    name: farol-backend
    env: python
    plan: starter
    region: oregon
    buildCommand: |
      pip install -r requirements.txt
    startCommand: python start.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: farol-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: RENDER
        value: true
      - key: CREATE_TEST_USER
        value: true
      - key: SEED_DATA
        value: true
    healthCheckPath: /health
    autoDeploy: true
    branch: main
    rootDir: ./backend

  # Frontend
  - type: web
    name: farol-frontend
    env: static
    plan: starter
    buildCommand: |
      npm install
      npm run build
    staticPublishPath: ./out
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://farol-backend.onrender.com
      - key: NODE_ENV
        value: production
      - key: RENDER
        value: true
    autoDeploy: true
    branch: main
    rootDir: ./frontend

  # Database
  databases:
    - name: farol-db
      databaseName: farol_db_data
      user: farol_user
      plan: starter
      region: oregon
      autoDeploy: true
